name: NPM Audit
on:
  schedule:
    - cron:  0 0 * * *
jobs:
  audit-generator:
    name: NPM Audit
    runs-on: [ubuntu-latest]
    env:
      BASE_PATH: ${{ secrets.BASE_PATH }}
      AUTH_USER_ID: ${{ secrets.AUTH_USER_ID }}
      AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
      ADMIN_APP_ID: ${{ secrets.ADMIN_APP_ID }}
      ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.1.0

      - run: npm ci
      - run: npm audit
      - run: npm run ci:build

  fix:
    name: NPM Audit fix
    runs-on: [ubuntu-latest]
    if: failure()
    steps:
      - run: npm audit fix
      - uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.PAT }}
          title: NPM Audit Vulnerability Found
