name: NPM Audit
on:
  schedule:
    - cron:  0 0 * * *
jobs:
  audit:
    name: NPM Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0

    - run: npm ci
    - run: npm audit
