name: Build
on:
  push:
    branches:
      - master
    tags:
      - "v*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BASE_PATH: ${{ secrets.BASE_PATH }}
      AUTH_USER_ID: ${{ secrets.AUTH_USER_ID }}
      AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
      ADMIN_APP_ID: ${{ secrets.ADMIN_APP_ID }}
      ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
      - run: echo "$BASE_PATH"
      - run: bun i --frozen-lockfile
      - run: bun run lint
      - run: bun run cd:build
      - name: 🚀 Publish to NPM
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          bun publish --access public ./admin-sdk
          bun publish --access public ./auth-sdk
          bun publish --access public ./issuance-sdk
