name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BASE_PATH: ${{ secrets.BASE_PATH }}
      AUTH_USER_ID: ${{ secrets.AUTH_USER_ID }}
      AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
      ADMIN_APP_ID: ${{ secrets.ADMIN_APP_ID }}
      ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1
      - run: echo "$BASE_PATH"
      - run: bun i --frozen-lockfile
      - run: bun run cd:build
