name: Build
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BASE_PATH: ${{ secrets.BASE_PATH }}
      AUTH_USER_ID: ${{ secrets.AUTH_USER_ID }}
      AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
      ADMIN_APP_ID: ${{ secrets.ADMIN_APP_ID }}
      ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
      - run: echo "$BASE_PATH"
      - run: |
          bun install --frozen-lockfile
          bun generate
          bun lint
          bun typecheck
          bun run build
          bun test
      - name: 🚀 Publish to NPM
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          bun publish --access public --cwd ./admin-sdk
          bun publish --access public --cwd ./auth-sdk
          bun publish --access public --cwd ./issuance-sdk
