name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BASE_PATH: ${{ secrets.BASE_PATH }}
      AUTH_USER_ID: ${{ secrets.AUTH_USER_ID }}
      AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
      ADMIN_APP_ID: ${{ secrets.ADMIN_APP_ID }}
      ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: echo "$BASE_PATH"
      - run: node -v
      - run: npm -v
      - run: npm ci
      - run: npm run cd:build
