name: build
on: [push]
env:
  BASE_PATH: ${{ secrets.BASE_PATH }}
  AUTH_USER_ID: ${{ secrets.AUTH_USER_ID }}
  AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
  ADMIN_APP_ID: ${{ secrets.ADMIN_APP_ID }}
  ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.1.0

      - run: node -v
      - run: npm -v
      - run: npm ci
      - run: npm run ci:build
