name: CI

permissions: {}

on:
  push:
    branches:
      - master

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_PATH: ${{ secrets.BASE_PATH }}
      AUTH_USER_ID: ${{ secrets.AUTH_USER_ID }}
      AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
      ADMIN_APP_ID: ${{ secrets.ADMIN_APP_ID }}
      ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck

      - name: Test
        run: bun run test
