name: CI
on: [push, check_run]
jobs:
  update:
    name: Update API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js
      uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run ci:build
