name: New Release Check
on:
  schedule:
    - cron: 0 21 * * *
env:
  BASE_PATH: ${{ secrets.BASE_PATH }}
  AUTH_USER_ID: ${{ secrets.AUTH_USER_ID }}
  AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
  ADMIN_APP_ID: ${{ secrets.ADMIN_APP_ID }}
  ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
jobs:
  update:
    name: API Update Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc # v1
      - run: bun i --frozen-lockfile
      - run: bun run download
      - uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50 # v6
        with:
          token: ${{ secrets.PAT }}
          title: New IDaaS API version
