name: New Release Check
on:
  schedule:
    - cron: 0 21 * * *
jobs:
  update:
    name: API Update Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
      - run: bun i --frozen-lockfile
      - run: bun run download
      - uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7
        with:
          token: ${{ secrets.PAT }}
          title: New IDaaS API version
