name: New Release Check
on:
  schedule:
    - cron: 0 21 * * *
jobs:
  update:
    name: API Update Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
      - run: bun install --frozen-lockfile
      - run: bun run download
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.PAT }}
          title: New IDaaS API version
          assignees: maccuaa
