name: New Release Check
on:
  schedule:
    - cron: 0 21 * * *
env:
  BASE_PATH: ${{ secrets.BASE_PATH }}
  AUTH_USER_ID: ${{ secrets.AUTH_USER_ID }}
  AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
  ADMIN_APP_ID: ${{ secrets.ADMIN_APP_ID }}
  ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
  ISSUANCE_APP_ID: ${{ secrets.ISSUANCE_APP_ID }}
  ISSUANCE_SECRET: ${{ secrets.ISSUANCE_SECRET }}
jobs:
  update:
    name: API Update Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
      - run: bun i --frozen-lockfile
      - run: bun run download
      - uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6
        with:
          token: ${{ secrets.PAT }}
          title: New IDaaS API version
