name: New Release Check
on:
  schedule:
    - cron: 0 21 * * *
env:
  BASE_PATH: ${{ secrets.BASE_PATH }}
  AUTH_USER_ID: ${{ secrets.AUTH_USER_ID }}
  AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
  ADMIN_APP_ID: ${{ secrets.ADMIN_APP_ID }}
  ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
  ISSUANCE_APP_ID: ${{ secrets.ISSUANCE_APP_ID }}
  ISSUANCE_SECRET: ${{ secrets.ISSUANCE_SECRET }}
jobs:
  update:
    name: API Update Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135 # v1
      - run: bun i --frozen-lockfile
      - run: bun run download
      - uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6
        with:
          token: ${{ secrets.PAT }}
          title: New IDaaS API version
