name: New Release Check
on:
  schedule:
    - cron: 0 21 * * *
env:
  BASE_PATH: ${{ secrets.BASE_PATH }}
  AUTH_USER_ID: ${{ secrets.AUTH_USER_ID }}
  AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
  ADMIN_APP_ID: ${{ secrets.ADMIN_APP_ID }}
  ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
jobs:
  update:
    name: API Update Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun -v
      - run: bun i
      - run: bun run download
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          title: New IDaaS API version
